version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  build:
    commands:
      - echo Running Tests
      - docker-compose run where-should-we-eat npm test
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -f Dockerfile-deploy -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG