version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the react code...
      - npm build
  post_build:
    commands:
      - echo Build completed on `date`